# Generated by Django 4.1.5 on 2023-01-10 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personas_fk_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="persona",
            name="edad",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
